export const businessmngConstants = {

    REGISTER_REQUEST1: 'CUSTOMER_REGISTER_REQUEST1',
    REGISTER_SUCCESS1: 'CUSTOMER_REGISTER_SUCCESS1',
    REGISTER_FAILURE1: 'CUSTOMER_REGISTER_FAILURE1',

    UPDATE_REQUEST1: 'CUSTOMER_UPDATE_REQUEST1',
    UPDATE_SUCCESS1: 'CUSTOMER_UPDATE_SUCCESS1',
    UPDATE_FAILURE1: 'CUSTOMER_UPDATE_FAILURE1',

    GETALL_REQUEST1: 'CUSTOMER_GETALL_REQUEST1',
    GETALL_SUCCESS1: 'CUSTOMER_GETALL_SUCCESS1',
    GETALL_FAILURE1: 'CUSTOMER_GETALL_FAILURE1',

    DELETE_REQUEST1: 'CUSTOMER_DELETE_REQUEST1',
    DELETE_SUCCESS1: 'CUSTOMER_DELETE_SUCCESS1',
    DELETE_FAILURE1: 'CUSTOMER_DELETE_FAILURE1',

    ACTIVATE_REQUEST1: 'CUSTOMER_ACTIVATE_REQUEST1',
    ACTIVATE_SUCCESS1: 'CUSTOMER_ACTIVATE_SUCCESS1',
    ACTIVATE_FAILURE1: 'CUSTOMER_ACTIVATE_FAILURE1',

    GET_REQUEST1: 'CUSTOMER_GET_REQUEST1',
    GET_SUCCESS1: 'CUSTOMER_GET_SUCCESSS1',
    GET_FAILURE1: 'CUSTOMER_GET_FAILURE1',

    GET_PROFILE_REQUEST1: 'CUSTOMER_PROFILE_REQUEST1',
    GET_PROFILE_SUCCESS1: 'CUSTOMER_PROFILE_SUCCESSS1',
    GET_PROFILE_FAILURE1: 'CUSTOMER_PROFILE_FAILURE1' ,

    GETLOCATION_REQUEST1: 'CUSTOMER_LOCATION_GET_REQUEST1',
    GETLOCATION_SUCCESS1: 'CUSTOMER_LOCATION_GET_SUCCESSS1',
    GETLOCATION_FAILURE1: 'CUSTOMER_LOCATION_GET_FAILURE1' 
};

