export const businessConstants = {

    REGISTER_REQUEST: 'BUSINESS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'BUSINESS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'BUSINESS_REGISTER_FAILURE',

    UPDATE_REQUEST: 'BUSINESS_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'BUSINESS_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'BUSINESS_UPDATE_FAILURE',

    GETALL_REQUEST: 'BUSINESS_GETALL_REQUEST',
    GETALL_SUCCESS: 'BUSINESS_GETALL_SUCCESS',
    GETALL_FAILURE: 'BUSINESS_GETALL_FAILURE',

    DELETE_REQUEST: 'BUSINESS_DELETE_REQUEST',
    DELETE_SUCCESS: 'BUSINESS_DELETE_SUCCESS',
    DELETE_FAILURE: 'BUSINESS_DELETE_FAILURE',

    ACTIVATE_REQUEST: 'BUSINESS_ACTIVATE_REQUEST',
    ACTIVATE_SUCCESS: 'BUSINESS_ACTIVATE_SUCCESS',
    ACTIVATE_FAILURE: 'BUSINESS_ACTIVATE_FAILURE',

    GET_REQUEST: 'BUSINESS_GET_REQUEST',
    GET_SUCCESS: 'BUSINESS_GET_SUCCESSS',
    GET_FAILURE: 'BUSINESS_GET_FAILURE',

    GETLOCATION_REQUEST: 'BUSINESS_LOCATION_GET_REQUEST',
    GETLOCATION_SUCCESS: 'BUSINESS_LOCATION_GET_SUCCESSS',
    GETLOCATION_FAILURE: 'BUSINESS_LOCATION_GET_FAILURE' 
};

