export const deviceConstants = {

    REGISTER_REQUEST: 'DEVICE_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'DEVICE_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'DEVICE_REGISTER_FAILURE',

    UPDATE_REQUEST: 'DEVICE_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'DEVICE_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'DEVICE_UPDATE_FAILURE',

    GETALL_REQUEST: 'DEVICE_GETALL_REQUEST',
    GETALL_SUCCESS: 'DEVICE_GETALL_SUCCESS',
    GETALL_FAILURE: 'DEVICE_GETALL_FAILURE',

    DELETE_REQUEST: 'DEVICE_DELETE_REQUEST',
    DELETE_SUCCESS: 'DEVICE_DELETE_SUCCESS',
    DELETE_FAILURE: 'DEVICE_DELETE_FAILURE',

    ACTIVATE_REQUEST: 'DEVICE_ACTIVATE_REQUEST',
    ACTIVATE_SUCCESS: 'DEVICE_ACTIVATE_SUCCESS',
    ACTIVATE_FAILURE: 'DEVICE_ACTIVATE_FAILURE',

    GET_REQUEST: 'DEVICE_GET_REQUEST',
    GET_SUCCESS: 'DEVICE_GET_SUCCESSS',
    GET_FAILURE: 'DEVICE_GET_FAILURE',

    GETLOCATION_REQUEST: 'DEVICE_LOCATION_GET_REQUEST',
    GETLOCATION_SUCCESS: 'DEVICE_LOCATION_GET_SUCCESSS',
    GETLOCATION_FAILURE: 'DEVICE_LOCATION_GET_FAILURE' 
};

