export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',
    
    UPDATE_REQUEST: 'USERS_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'USERS_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'USERS_UPDATE_FAILURE',

    FORGOTPASSWORD_REQUEST: 'USERS_FORGOTPASSWORD_REQUEST',
    FORGOTPASSWORD_SUCCESS: 'USERS_FORGOTPASSWORDR_SUCCESS',
    FORGOTPASSWORD_FAILURE: 'USERS_FORGOTPASSWORD_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    
    LOGOUT: 'USERS_LOGOUT',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE',

    ACTIVATE_REQUEST: 'USERS_ACTIVATE_REQUEST',
    ACTIVATE_SUCCESS: 'USERS_ACTIVATE_SUCCESS',
    ACTIVATE_FAILURE: 'USERS_ACTIVATE_FAILURE',

    GETUSER_REQUEST: 'USER_GET_REQUEST',
    GETUSER_SUCCESS: 'USER_GET_SUCCESSS',
    GETUSER_FAILURE: 'USER_GET_FAILURE',

    GET_PROFILE_REQUEST: 'USER_PROFILE_REQUEST',
    GET_PROFILE_SUCCESS: 'USER_PROFILE_SUCCESSS',
    GET_PROFILE_FAILURE: 'USER_PROFILE_FAILURE' ,

    GET_USERINFO_REQUEST: 'USER_USERINFO_REQUEST',
    GET_USERINFO_SUCCESS: 'USER_USERINFO_SUCCESSS',
    GET_USERINFO_FAILURE: 'USER_USERINFO_FAILURE' ,
};

