export const visitorConstants = {

    REGISTER_REQUEST: 'VISITOR_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'VISITOR_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'VISITOR_REGISTER_FAILURE',

    UPDATE_REQUEST: 'VISITOR_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'VISITOR_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'VISITOR_UPDATE_FAILURE',

    GETALL_REQUEST: 'VISITOR_GETALL_REQUEST',
    GETALL_SUCCESS: 'VISITOR_GETALL_SUCCESS',
    GETALL_FAILURE: 'VISITOR_GETALL_FAILURE',

    DELETE_REQUEST: 'VISITOR_DELETE_REQUEST',
    DELETE_SUCCESS: 'VISITOR_DELETE_SUCCESS',
    DELETE_FAILURE: 'VISITOR_DELETE_FAILURE',

    ACTIVATE_REQUEST: 'VISITOR_ACTIVATE_REQUEST',
    ACTIVATE_SUCCESS: 'VISITOR_ACTIVATE_SUCCESS',
    ACTIVATE_FAILURE: 'VISITOR_ACTIVATE_FAILURE',

    GET_REQUEST: 'VISITOR_GET_REQUEST',
    GET_SUCCESS: 'VISITOR_GET_SUCCESSS',
    GET_FAILURE: 'VISITOR_GET_FAILURE',

    GETLOCATION_REQUEST: 'VISITOR_LOCATION_GET_REQUEST',
    GETLOCATION_SUCCESS: 'VISITOR_LOCATION_GET_SUCCESSS',
    GETLOCATION_FAILURE: 'VISITOR_LOCATION_GET_FAILURE' 
};

