export const customerConstants = {

    REGISTER_REQUEST: 'CUSTOMER_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'CUSTOMER_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'CUSTOMER_REGISTER_FAILURE',

    UPDATE_REQUEST: 'CUSTOMER_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'CUSTOMER_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'CUSTOMER_UPDATE_FAILURE',

    GETALL_REQUEST: 'CUSTOMER_GETALL_REQUEST',
    GETALL_SUCCESS: 'CUSTOMER_GETALL_SUCCESS',
    GETALL_FAILURE: 'CUSTOMER_GETALL_FAILURE',

    DELETE_REQUEST: 'CUSTOMER_DELETE_REQUEST',
    DELETE_SUCCESS: 'CUSTOMER_DELETE_SUCCESS',
    DELETE_FAILURE: 'CUSTOMER_DELETE_FAILURE',

    ACTIVATE_REQUEST: 'CUSTOMER_ACTIVATE_REQUEST',
    ACTIVATE_SUCCESS: 'CUSTOMER_ACTIVATE_SUCCESS',
    ACTIVATE_FAILURE: 'CUSTOMER_ACTIVATE_FAILURE',

    GET_REQUEST: 'CUSTOMER_GET_REQUEST',
    GET_SUCCESS: 'CUSTOMER_GET_SUCCESSS',
    GET_FAILURE: 'CUSTOMER_GET_FAILURE',

    GET_PROFILE_REQUEST: 'CUSTOMER_PROFILE_REQUEST',
    GET_PROFILE_SUCCESS: 'CUSTOMER_PROFILE_SUCCESSS',
    GET_PROFILE_FAILURE: 'CUSTOMER_PROFILE_FAILURE' ,

    GETLOCATION_REQUEST: 'CUSTOMER_LOCATION_GET_REQUEST',
    GETLOCATION_SUCCESS: 'CUSTOMER_LOCATION_GET_SUCCESSS',
    GETLOCATION_FAILURE: 'CUSTOMER_LOCATION_GET_FAILURE' 
};

